edx_arch_experiments/kafka_consumer/docs/decisions/0002_kafka_consumer_command.rst
Provide details around the rejected alternative
of using a scheduled celery task as our Kafka
consumer.
=> docs: reject celery for Kafka consumer

Makefile, requirements/pip-tools.txt
Add upgrade_package target to Makefile for upgrading a specific package to the latest version.
Usage: `make upgrade_package package=my-package`
=> feat: add upgrade_package target to Makefile

edx_arch_experiments/kafka_consumer/docs/decisions/0002_kafka_consumer_command.rst
Adds some additional notes about this decision based
on some discussions. Clarifies some of the potential
complexities around deployments.
=> docs: add consequence to consumer ADR

.github/workflows/escalate.yml
This is meant to be a way to test an initial implementation of https://github.com/edx/edx-arch-experiments/issues/119 since I don't think I can trigger a branch workflow by labeling an issue.
Will revert once I verify that it works, and then 
1. get a service account
2. replace my email and token with said account
3. update to file issues to PSRE instead of ARCHBOM
=> temp: test workflow to create Jira tickets from labeled issues

.github/workflows/escalate.yml
Issue: https://github.com/edx/edx-arch-experiments/issues/119
The user is recently created by IT and the scope of what we should use it for is not 100% determined but @nedbat and I determined that it makes sense to use it here.
=> feat: use new service account in escalate action

.github/workflows/escalate.yml
Issue: https://github.com/edx/edx-arch-experiments/issues/119
Fix escalate action to create in PSRE instead of ARCHBOM project. ARCHBOM was originally used to test the flow but PSRE is the correct destination.
=> fix: escalate to PSRE instead of ARCHBOM

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/summaryhook_aside/block.py
We will be building a path for ai-spot to get content from edx rather than having it pushed by the browser, including video transcripts.
To demo that quickly we're going to populate selected course content into a temp store in ai-spot and it will fetch from a local fake edx.
So this change removes the local content indicator and triggers on any video and summaries will for a while only work on the pre-fetched while we catch up the rest of the content path.
Tested locally to verify appearance of aside div.
=> feat: trigger summary block on any video, remove content pointer

CHANGELOG.rst, edx_arch_experiments/scripts/get_action_errors.py
See diff for a fuller description of what the script does.
To run, make sure you have your GITHUB_TOKEN set in the environment.
Example output: https://docs.google.com/spreadsheets/d/1GBfLjpxx-r8lAohevpNCZhYFeETpk4imAxUbn87uumg/edit#gid=1755866686
=> feat: add script to get annotations from errored actions

edx_arch_experiments/scripts/generate_code_owner_mappings.py
Fixes missing code_owner for:
- `"code_owner_module": "edx_recommendations.api.course_recommendations",`
- `"name": "WebTransaction/Function/edx_recommendations.api.course_recommendations:LearnerDashboardRecommendationsView.get",`
=> feat: add edx_recommendations to generate_code_owner_mappings.py

README.rst, edx_arch_experiments/scripts/republish_failed_events.py
feat: abstract out the producer when republishing events
Use openedx-events.get_producer() instead of calling event bus kafka directly so it can be used with redis or other implementations.
=> feat: abstract out producer creation

Dockerfile, Makefile, README.rst, docker-compose.yml
Adds a `make test-shell` which launches a dockerized version of the local dev environment - rather than using a local virtualenv.
~ Working from https://github.com/openedx/edx-enterprise/pull/1467 ~
There are sometimes benefits and conveniences to having a containerized local environment versus setting up and maintaining python, virtualenv, and system dependencies (mysql-dev, etc) natively. Sometimes installing your code into the LMS container extends your testing cycle past your patience. Here is some docker/makefile config to enable make test-shell to launch a containerized environment containing your local development code so you can make test / make upgrade / 'profit' / etc inside a container.
**pytest**
```
ubuntu@ip-172-31-38-188:~/edx-repos/edx-arch-experiments$ make test-shell …
```
=> feat: docker-based local work without lms

edx_arch_experiments/scripts/generate_code_owner_mappings.py
We're getting alerts for Celery transactions with a `code_owner_module` of `openassessment.workflow.tasks` but no mapped code owner. While `openassessment` isn't an app, this might be the right way to fix this?
=> feat: Add ora2 openassessment mapping

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/config_watcher/apps.py, edx_arch_experiments/config_watcher/signals/receivers.py, setup.py
- ConfigWatcher needs to be configured as a plugin to be loaded into edxapp, since we don't use INSTALLED_APPS for this dependency.
- On the renaming: This is the name I actually meant to write in the first place.
- Remove some fields that are less likely to be interesting and are likely to just result in clutter.
----
Re-tested in devstack. This time, I only had to add the `CONFIG_WATCHER_SLACK_WEBHOOK_URL` setting in order for the plugin to activate -- no need to add to INSTALLED_APPS.
----
=> feat!: Rename ConfigWatcher app and configure as plugin; reduce fields

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/config_watcher/signals/receivers.py
- Add log message for each model the ConfigWatcher is listening to, mostly so I can tell whether this app is even getting loaded.
- Add dispatch_uid to receivers so that if `ready` (or `connect_receivers`) is called more than once, the receiver is only attached once. (This is not a response to an observed problem -- it's just a best practice according to Django docs.)
=> feat: Log addition of config watchers and make receivers unique

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/config_watcher/signals/receivers.py
These inner functions would otherwise get GC'd right away, since Django only holds weak references to receivers by default. (I don't know why this worked in devstack.)
=> fix: ConfigWatcher needs to register receivers using strong references

.annotation_safe_list.yml, .gitignore, .pii_annotations.yml, tox.ini
Copied code from cookiecutter-django-app.
=> build: Fix `make test-all` by implementing pii_check

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/config_watcher/README.rst, edx_arch_experiments/config_watcher/signals/receivers.py, edx_arch_experiments/config_watcher/signals/tests/test_receivers.py, setup.py
Introduces `CONFIG_WATCHER_SERVER_NAME` to support messaging from multiple services.
=> feat: Enable ConfigWatcher in CMS; prefix Slack messages with IDA name

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/datadog_diagnostics/README.rst, edx_arch_experiments/datadog_diagnostics/apps.py, setup.py
See https://github.com/edx/edx-arch-experiments/issues/692
Testing setup:
https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1173618788/Running+Datadog+in+devstack
And then in lms-shell:
```
make requirements
pip install ddtrace
pip install -e /edx/src/archexp/
./wrap-datadog.sh ./server.sh
```
Expect to see this log message:
`Attached MissingSpanProccessor for Datadog diagnostics`
:warning: This prints "Spans created = 0; spans finished = 0" in devstack when shut down with ctrl-c, but not when restarted due to autoreload (where it prints correct info). Something is initializing Django twice and one span processor is getting span info while the other is printing at shutdown. There's more to debug here, but it seems stable enough to least try deploying it.
Check …
=> feat: Add datadog_diagnostics plugin app

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/datadog_diagnostics/apps.py, edx_arch_experiments/datadog_diagnostics/tests/test_app.py
- Add `DATADOG_DIAGNOSTICS_ENABLE` for quick disable if needed
- Limit spans with `DATADOG_DIAGNOSTICS_MAX_SPANS` (default 100)
- Fix scope of member variables
- Add unit tests
Manual testing:
- Modify `common.djangoapps.student.views.dashboard.student_dashboard` in edx-platform to call `import time; time.sleep(10)` at the start of the view.
- Start server and log
- Visit /dashboard
- While the browser is waiting, quickly make a small edit to an edx-platform file, causing an autoreload.
- Confirm that spans are logged.
=> feat: Robustness improvements to datadog_diagnostics plugin

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/datadog_diagnostics/apps.py, edx_arch_experiments/datadog_diagnostics/tests/test_app.py
I still don't understand why this setting loading was broken -- maybe there's something unusual about the way plugin apps are loaded?
This addresses https://github.com/edx/edx-arch-experiments/issues/771
=> fix: Remove early span-start logging; fix loading of Django settings

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/datadog_diagnostics/apps.py, edx_arch_experiments/datadog_diagnostics/tests/test_app.py, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/scripts.txt, requirements/test.in, requirements/test.txt
Adds celery as a testing dependency.
Manually tested using http://localhost:18000/courses/course-v1:edX+M12+2T2023/instructor#view-data_download in devstack.
=> feat: Add celery task lifecycle logging for Datadog diagnostics

CHANGELOG.rst, edx_arch_experiments/__init__.py, edx_arch_experiments/datadog_diagnostics/middleware.py, edx_arch_experiments/datadog_diagnostics/tests/test_middleware.py
Datadog believes that a lingering unfinished celery span from a previous request might be becoming the active context for all future Django requests, causing them to become parented to it. To gather evidence, we'll need to learn not just what the trace root span is, but whether there are unexpected intermediary spans as well.
There may be a great many ancestors, especially with the trace concatenation in play, so we'll walk upwards from the current span towards the root until a limit is reached. This should allow us to find if the current Django request's span has a parent, and what it is.
- New setting `DATADOG_DIAGNOSTICS_LOG_SPAN_DEPTH` to control walk depth
- Move anomaly logging to its own method.
- Log ancestry of N proximal spans, and adjust formatting of logging to be more …
=> feat: Log ancestors of current span when anomaly found

edx_arch_experiments/datadog_diagnostics/tests/test_app.py, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/scripts.txt, requirements/test.in, requirements/test.txt, tox.ini
This will help catch this sort of problem in the future, with the downside that it may cause a test failure to first be seen on someone else's PR...
=> test: Fix order sensitivity in tests due to stale state; randomize tests

edx_arch_experiments/datadog_diagnostics/vendor/README.rst
I picked this wheel because I see `EDXAPP_PYTHON_VERSION: "python3.11"` in the configuration repo, and no overrides. The wheel is the artifact named `wheels-cp311-manylinux_x86_64` from branch build
<https://github.com/DataDog/dd-trace-py/actions/runs/10997116239>.
=> feat: Add vendored release candidate of ddtrace that may fix celery spans

CHANGELOG.rst, edx_arch_experiments/datadog_monitoring/docs/how_tos/search_datadog.rst, edx_arch_experiments/datadog_monitoring/docs/how_tos/update_monitoring_for_squad_or_theme_changes.rst, edx_arch_experiments/datadog_monitoring/scripts/datadog_search.py
A search script for searching Datadog
monitors and dashboards.
Implements:
- https://github.com/edx/edx-arch-experiments/issues/786
**Sample script output:**
Note: This sample output is slightly out of date.
- It is missing the final output of match counts.
- There _may_ be other minor differences.
```
% python datadog_search.py --regex "code_owner[^_]"
Searching for regex code_owner([^_]|\b) in all monitors:
.........................................................
...
- 99999999 "LMS missing code owner transactions" ['team:arch-bom', 'service:edx-edxapp-lms', 'operation_name:django.request']
- match_path: monitor.query
- match: trace-analytics("@_top_level:1 env:(prod OR edge) service:edx-edxapp-lms -@code_owner:* -@http.status_code:(30* OR 40*) @http.status_code:* …
```
=> feat: add Datadog search script

requirements/dev.in, requirements/dev.txt
It still makes sense for the script to explicitly call out this dependency in its --help message, but we can also install the dep automatically for people calling it from the context of a fully installed venv for this repo.
=> feat: Add datadog-api-client to dev deps so script is easier to use

CHANGELOG.rst, edx_arch_experiments/datadog_monitoring/code_owner/utils.py, edx_arch_experiments/datadog_monitoring/tests/code_owner/test_utils.py
The span tag code_owner_plugin was used to rollout code_owner switch from edx-django-utils to the
datadog_monitoring plugin in this repo. Now that
rollout is complete, this span tag can be removed.
Implements:
- https://github.com/edx/edx-arch-experiments/issues/784
=> feat!: remove temporary rollout span tag code_owner_plugin

edx_arch_experiments/scripts/generate_code_owner_mappings.py
Underscores instead of hyphens
=> fix: Correct module name for federated_content_connector

.github/dependabot.yml, .github/workflows/upgrade-python-requirements.yml
Description
Update GitHub workflow failure email notifications to use orbi-bom's JSM email instead of [arbi-bom@edx.org](mailto:arbi-bom@edx.org) 
Changes team reviewer assignments from arbi-bom to orbi-bom in dependency management workflows
Related PRs
https://github.com/edx/api-manager/pull/354
https://github.com/edx/devstack/pull/174
https://github.com/edx/edx-internal/pull/13377
https://github.com/edx/repo-health-data/pull/312
https://github.com/edx/jenkins-job-dsl-internal/pull/962
Jira - [BOMS-39](https://2u-internal.atlassian.net/browse/BOMS-39)
[BOMS-39]: https://2u-internal.atlassian.net/browse/BOMS-39
=> chore: BOMS-39 rename arbi-bom to orbi-bom
